title: Барабаш Олег Володимирович
#email: barabash-oleg@lll.kpi.ua
description: Сайт для студентів
theme: just-the-docs
#repository: BarabashOleg/website
#remote_theme: pages-themes/cayman@v0.2.0
#github: [metadata]
#domain: barabasholeg.github.io
url: https://barabasholeg.github.io/

search_enabled: false
